const simpleObject={
    name: 'Loui',
    mobile: '09915718935',
    greet(){
        console.log(`Hello my name is: ${this.name}`);
    }
}


//inputs:
first name, middle name, lastname, phone, address 
//sample table display
first name| middle name| lastname| phone| address
james     | hiller | miller | 0909009| ormoc
james     | hiller | miller | 0909009| ormoc
james     | hiller | miller | 0909009| ormoc
james     | hiller | miller | 0909009| ormoc
james     | hiller | miller | 0909009| ormoc
james     | hiller | miller | 0909009| ormoc
james     | hiller | miller | 0909009| ormoc